"""empty message

Revision ID: 63471a8c876f
Revises: 82063b2e30fc
Create Date: 2019-12-02 19:19:21.272590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63471a8c876f'
down_revision = '82063b2e30fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('City', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('City', 'num_upcoming_shows')
    # ### end Alembic commands ###
